'use strict';
const data=JSON.parse(document.querySelector('#wedding-data').textContent);
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
let toastTimer;
function notify(text){const t=document.querySelector('#toast');t.textContent=text;t.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('visible'),2600);}
const date=new Date(data.date);
const [year,month,day]=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(date).split('-').map(Number);
const calendar=document.querySelector('#calendar');
for(const name of ['일','월','화','수','목','금','토'])calendar.append(el('span',name,'weekday'));
const offset=new Date(Date.UTC(year,month-1,1)).getUTCDay();
for(let i=0;i<offset;i++){const blank=el('span','');blank.setAttribute('aria-hidden','true');calendar.append(blank);}
for(let i=1;i<=new Date(Date.UTC(year,month,0)).getUTCDate();i++){const cell=el('span',String(i),i===day?'wedding-day':'');if(i===day)cell.setAttribute('aria-label',`${month}월 ${i}일 결혼식`);calendar.append(cell);}
for(const [title,body]of Object.entries(data.transport)){const group=el('div');group.append(el('h3',title),el('p',body));document.querySelector('#directions').append(group);}
for(const account of data.accounts){const row=el('div',undefined,'account');const detail=el('div');const heading=el('p');heading.append(el('span',`${account.side}측`,'account-side'),el('span',account.name,'account-name'));detail.append(heading,el('p',`${account.bank} ${account.number}`,'account-number'));const button=el('button','복사','copy-button');button.type='button';button.setAttribute('aria-label',`${account.name} 계좌번호 복사`);button.addEventListener('click',async()=>{try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(account.number);else{const input=el('textarea',account.number);input.style.position='fixed';input.style.opacity='0';document.body.append(input);input.select();const copied=document.execCommand('copy');input.remove();button.focus();if(!copied)throw Error('copy failed');}notify('계좌번호를 복사했어요.');}catch{notify('복사하지 못했어요. 계좌번호를 길게 눌러 복사해주세요.');}});row.append(detail,button);document.querySelector('#accounts').append(row);}
const dialog=document.querySelector('#photo-dialog');let currentPhoto=0;let lastPhotoButton;
function showPhoto(index){currentPhoto=(index+data.photos.length)%data.photos.length;const photo=data.photos[currentPhoto];document.querySelector('#large-photo').src=photo.src;document.querySelector('#large-photo').alt=photo.alt;document.querySelector('#photo-counter').textContent=`${currentPhoto+1} / ${data.photos.length}`;}
data.photos.forEach((photo,index)=>{const button=el('button');button.type='button';button.setAttribute('aria-label',`${photo.alt}, 크게 보기`);const img=el('img');img.src=photo.src;img.alt=photo.alt;img.width=1122;img.height=1402;img.loading='lazy';img.decoding='async';button.append(img);button.addEventListener('click',()=>{lastPhotoButton=button;showPhoto(index);dialog.showModal();});document.querySelector('#gallery').append(button);});
document.querySelector('#close-photo').addEventListener('click',()=>dialog.close());
document.querySelector('#prev-photo').addEventListener('click',()=>showPhoto(currentPhoto-1));
document.querySelector('#next-photo').addEventListener('click',()=>showPhoto(currentPhoto+1));
dialog.addEventListener('keydown',event=>{if(event.key==='ArrowLeft')showPhoto(currentPhoto-1);if(event.key==='ArrowRight')showPhoto(currentPhoto+1);});
dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}});
dialog.addEventListener('close',()=>lastPhotoButton?.focus());
let touchX=0;document.querySelector('#large-photo').addEventListener('touchstart',event=>{touchX=event.changedTouches[0].screenX;},{passive:true});document.querySelector('#large-photo').addEventListener('touchend',event=>{const difference=event.changedTouches[0].screenX-touchX;if(Math.abs(difference)>60)showPhoto(currentPhoto+(difference<0?1:-1));},{passive:true});
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');if(!matchMedia('(prefers-reduced-motion: reduce)').matches)entry.target.classList.add('enter');observer.unobserve(entry.target);}});},{threshold:.12});document.querySelectorAll('.section,.gallery-heading').forEach(n=>observer.observe(n));}else document.querySelector('.date').classList.add('is-visible');
async function request(path,options={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(`/api/${path}`,{...options,signal:controller.signal,headers:{'Content-Type':'application/json',...options.headers}});const result=await response.json();if(!response.ok){const error=new Error(result.error||'잠시 후 다시 시도해주세요.');error.status=response.status;throw error;}return result;}catch(error){if(error.name==='AbortError')throw new Error('연결이 지연되고 있어요. 잠시 후 다시 시도해주세요.');throw error;}finally{clearTimeout(timer);}}
const storage={get(key){try{return localStorage.getItem(key);}catch{return null;}},set(key,value){try{localStorage.setItem(key,value);}catch{}}};
function sentState(form,status,message){form.querySelectorAll('input,select,button').forEach(n=>n.disabled=true);status.textContent=message;}
function setupForm(id,path,createPayload,success){const form=document.querySelector(`#${id}-form`);const status=document.querySelector(`#${id}-status`);const key=`wedding-${data.date}-${path}-sent`;if(storage.get(key))sentState(form,status,success);form.addEventListener('submit',async event=>{event.preventDefault();if(!form.reportValidity())return;const button=form.querySelector('button[type=submit]');if(button.disabled)return;const values=new FormData(form);if(!values.get('name').trim()||(path==='guestbook'&&!values.get('message').trim())){status.textContent='공백만 입력할 수 없어요.';return;}button.disabled=true;status.textContent='마음을 전하고 있어요…';try{await request(path,{method:'POST',body:JSON.stringify(createPayload(values))});storage.set(key,'1');sentState(form,status,success);if(path==='guestbook')await loadGuestbook();}catch(error){if(error.status===409){storage.set(key,'1');sentState(form,status,'이미 마음을 전해주셨어요. 감사합니다.');}else{status.textContent=error.message||'연결을 확인하고 다시 시도해주세요.';button.disabled=false;}}});}
setupForm('rsvp','rsvp',v=>({name:v.get('name').trim(),count:Number(v.get('count')),meal:v.get('meal')==='yes'}),'참석 소식을 잘 받았습니다. 그날 반갑게 만나요.');
setupForm('guestbook','guestbook',v=>({name:v.get('name').trim(),message:v.get('message').trim()}),'따뜻한 마음을 남겨주셔서 감사합니다.');
async function loadGuestbook(){const list=document.querySelector('#guestbook-list');const button=document.querySelector('#refresh-guestbook');button.disabled=true;try{const rows=await request('guestbook');list.replaceChildren();if(!rows.length)list.append(el('p','첫 번째 축하 메시지를 남겨주세요.','empty-state'));for(const row of rows){const article=el('article',undefined,'guest-message');const header=el('header');const time=el('time',new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit'}).format(new Date(row.created_at)));time.dateTime=row.created_at;header.append(el('strong',row.name),time);article.append(header,el('p',row.message));list.append(article);}}catch{list.replaceChildren(el('p','메시지를 불러오지 못했어요. 아래 버튼을 눌러 다시 시도해주세요.','empty-state'));}finally{button.disabled=false;}}
document.querySelector('#refresh-guestbook').addEventListener('click',loadGuestbook);loadGuestbook();
